apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - env-patch.yaml
images:
  - name: harbor.setokaibas.com/projet-dns/dns-lookup
    newTag: 20260105-200723-31b61c64 # Sera mis à jour par le CI
