apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- env-patch.yaml
images:
- name: harbor.setokaibas.com/projet-dns/dns-lookup
  newTag: latest   # Sera mis à jour par le CI